#Kibana for b2c load test

FROM docker.elastic.co/kibana/kibana:6.3.2

MAINTAINER Nobuki Hara <hara.nobuki.a9n@jp.nssol.nssmc.com>

#RUN bin/kibana-plugin install x-pack
RUN bin/kibana-plugin install https://github.com/sivasamyk/logtrail/releases/download/v0.1.29/logtrail-6.3.2-0.1.29.zip
