version: '2'
services:
 elasticsearch03:
   image: bcc/elasticsearch:v1.0
   environment:
     - network.host=_eth0:ipv4_
     - bootstrap.memory_lock=true
     - cluster.name=bcc-cluster
     - discovery.zen.minimum_master_nodes=2
     - discovery.zen.ping.unicast.hosts=10.7.0.137:9300,10.7.0.137:9301,10.7.0.208:9300
     #- node.master=true
     #- node.data=true
     #- node.ingest=false
     #- node.ml=false
     - http.host=0.0.0.0
     - transport.host=0.0.0.0
     - xpack.security.enabled=false
     #- xpack.monitoring.enabled=true
     - xpack.watcher.enabled=false
     - xpack.graph.enabled=false
     - xpack.ml.enabled=false
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
   ports:
     - 9200:9200
     - 9300:9300
   volumes:
     - es-data03:/usr/share/elasticsearch/data
   logging:
     driver: "json-file"
   ulimits:
     nproc: 65536
     nofile:
       soft: 65536
       hard: 65536
     memlock:
      soft: -1
      hard: -1
   network_mode: "host"

volumes:
  es-data03:
    driver: local
